apiVersion: v1
kind: Secret
metadata:
  name: px-vsphere-secret
  namespace: kube-system
type: Opaque
data:
  VSPHERE_USER: [replace:echo -n <vcenter-server-user> | base64]
  VSPHERE_PASSWORD: [replace:echo -n <vcenter-server-password> | base64]
