# This consistent snapshot group will snapshot ALL
# volumes with label `db-group: db-data`
# as a consistent portworx local snapgroup
apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: wp-mysql-snapshot-group
  namespace: default
  annotations:
    portworx/snapshot-type: local
    portworx.selector/app-group: wordpress
spec:
  persistentVolumeClaimName: wordpress-snapgroup
